# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("statistics", "0010_existing_case_timings_count")]

    operations = [
        migrations.AlterField(model_name="dailysecondtotalcount", name="seconds", field=models.BigIntegerField())
    ]
