# Generated by Django 2.2.8 on 2019-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0013_auto_20191209_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycount", name="is_squashed", field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="dailysecondtotalcount",
            name="is_squashed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="totalcount", name="is_squashed", field=models.BooleanField(default=False, null=True),
        ),
    ]
