# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_auto_20161014_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='summary',
            field=models.TextField(verbose_name='Summary'),
        ),
    ]
