# Generated by Django 2.0.8 on 2018-08-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("orgs", "0026_fix_org_config_rapidpro"), ("cases", "0046_iso639_3")]

    operations = [
        migrations.AddField(
            model_name="caseaction",
            name="org",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="actions", to="orgs.Org"
            ),
        )
    ]
