# Generated by Django 2.0.8 on 2018-08-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cases", "0048_backfill_action_org")]

    operations = [
        migrations.AlterField(
            model_name="caseaction",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="actions", to="orgs.Org"
            ),
        ),
        migrations.AddIndex(
            model_name="caseaction",
            index=models.Index(fields=["org", "-created_on"], name="cases_casea_org_id_4dee78_idx"),
        ),
    ]
