# Generated by Django 2.0.8 on 2018-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0049_auto_20180822_1513")]

    operations = [
        migrations.AddIndex(
            model_name="case", index=models.Index(fields=["org", "-opened_on"], name="cases_case_org_id_bd42e2_idx")
        )
    ]
