# Generated by Django 2.2.8 on 2019-12-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0050_auto_20180822_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseexport",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="caseexports", to="orgs.Org"
            ),
        ),
    ]
