# Generated by Django 4.0.1 on 2022-01-12 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0030_alter_invitation_created_by_and_more"),
        ("cases", "0051_auto_20191216_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseexport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="caseexport",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="orgs.org"
            ),
        ),
        migrations.AlterField(
            model_name="caseexport",
            name="partner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)ss", to="cases.partner"
            ),
        ),
    ]
