# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0053_faq")]

    operations = [migrations.AlterField(model_name="outgoing", name="text", field=models.TextField(max_length=800))]
