# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0053_message_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='actioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
