# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0055_auto_20170117_1418")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="modified_on",
            field=models.DateTimeField(help_text="When message was last modified", null=True),
        )
    ]
