# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0055_auto_20170117_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='actioned_by',
            new_name='locked_by',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='last_action',
            new_name='locked_on',
        ),
    ]
