# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0018_auto_20170301_0914"), ("msgs", "0056_message_modified_on")]

    operations = [migrations.AlterIndexTogether(name="message", index_together=set([("org", "modified_on")]))]
