# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0057_auto_20170718_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='handled_on',
            field=models.DateTimeField(null=True),
        ),
    ]
