# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0059_new_modified_msgs_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgs.Label')),
            ],
            options={
                'db_table': 'msgs_message_labels',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='labels',
            field=models.ManyToManyField(help_text='Labels assigned to this message', related_name='messages', through='msgs.Labelling', to='msgs.Label'),
        ),
        migrations.AddField(
            model_name='labelling',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgs.Message'),
        ),
    ]
