# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0059_new_modified_msgs_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelling',
            name='message_created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
