# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 22:10
from __future__ import unicode_literals, print_function

from django.db import migrations, transaction
from dash.utils import chunks


def backfill_labelling_created_on(apps, schema_editor):
    Labelling = apps.get_model('msgs', 'Labelling')

    all_labellings = Labelling.objects.filter(message_created_on=None)
    total_count = all_labellings.count()
    if not total_count:
        return

    print("Found %d labellings to update..." % total_count)

    num_updated = 0
    for batch_ids in chunks(all_labellings.values_list('id', flat=True).iterator(), 1000):
        labellings = Labelling.objects.filter(id__in=batch_ids).prefetch_related('message')

        with transaction.atomic():
            for labelling in labellings:
                labelling.message_created_on = labelling.message.created_on
                labelling.save(update_fields=('message_created_on',))
                num_updated += 1

        print(" > Updated %d of %d labellings" % (num_updated, total_count))


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0060_labelling_message_created_on'),
    ]

    operations = [
        migrations.RunPython(backfill_labelling_created_on)
    ]
