# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0061_backfill_labelling_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelling',
            name='message_created_on',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='labelling',
            index=models.Index(fields=['label', '-message_created_on'], name='msgs_messag_label_i_e44df4_idx'),
        ),
    ]
