# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0062_auto_20180126_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelling',
            name='label',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='msgs.Label'),
        ),
    ]
