# Generated by Django 2.2.8 on 2019-12-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0064_populate_labelling"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="labelling",
            index=models.Index(
                condition=models.Q(message_is_archived=False),
                fields=["label", "-message_created_on"],
                name="labelling_inbox",
            ),
        ),
        migrations.AddIndex(
            model_name="labelling",
            index=models.Index(
                condition=models.Q(message_is_archived=True),
                fields=["label", "-message_created_on"],
                name="labelling_archived",
            ),
        ),
        migrations.AddIndex(
            model_name="labelling",
            index=models.Index(
                condition=models.Q(("message_is_archived", False), ("message_is_flagged", True)),
                fields=["label", "-message_created_on"],
                name="labelling_flagged",
            ),
        ),
        migrations.AddIndex(
            model_name="labelling",
            index=models.Index(
                condition=models.Q(message_is_flagged=True),
                fields=["label", "-message_created_on"],
                name="labelling_flagged_w_archived",
            ),
        ),
        migrations.AlterField(model_name="labelling", name="message_created_on", field=models.DateTimeField(),),
        migrations.AlterField(model_name="labelling", name="message_is_archived", field=models.BooleanField(),),
        migrations.AlterField(model_name="labelling", name="message_is_flagged", field=models.BooleanField(),),
    ]
