# Generated by Django 4.0.8 on 2023-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0067_alter_messageexport_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoing",
            name="backend_id",
            field=models.IntegerField(null=True),
        ),
    ]
