# Generated by Django 2.0.8 on 2018-08-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("msg_board", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="messageboardcomment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_set_for_messageboardcomment",
                to="contenttypes.ContentType",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="messageboardcomment",
            name="site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sites.Site"),
        ),
    ]
