# Generated by Django 2.2.19 on 2021-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msg_board", "0002_auto_20180814_2109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageboardcomment",
            name="is_removed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.',
                verbose_name="is removed",
            ),
        ),
        migrations.AlterField(
            model_name="messageboardcomment",
            name="object_pk",
            field=models.CharField(db_index=True, max_length=64, verbose_name="object ID"),
        ),
    ]
