-- Generated by collect_sql on 2021-07-12 22:09 UTC

CREATE TRIGGER msgs_message_labels_on_change_trg
   AFTER INSERT OR DELETE ON msgs_message_labels
   FOR EACH ROW EXECUTE PROCEDURE msgs_message_labels_on_change();

CREATE TRIGGER msgs_message_labels_on_truncate_trg
  AFTER TRUNCATE ON msgs_message_labels
  EXECUTE PROCEDURE msgs_message_labels_on_change();

CREATE TRIGGER msgs_message_on_change_trg
   AFTER UPDATE ON msgs_message
   FOR EACH ROW EXECUTE PROCEDURE msgs_message_on_change();

