# Generated by Django 2.0.8 on 2018-08-21 18:33

from django.db import migrations
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token


def generate_tokens(apps, scheme_editor):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [("profiles", "0008_profile_must_use_faq")]

    operations = [migrations.RunPython(generate_tokens)]
